<a href="https://colab.research.google.com/github/Edgar0617/Platzi/blob/master/Conditions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
arr = np.linspace(1,10,10, dtype = "int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [17]:
indices_cond = arr < 5
indices_cond

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [22]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [25]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [30]:
hola = arr[arr == 99]
hola

array([99, 99, 99, 99, 99], dtype=int8)