<a href="https://colab.research.google.com/github/Edgar0617/Platzi/blob/master/Creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2,4)

array([[0.45704055, 0.77054257, 0.96137114, 0.48411278],
       [0.57985635, 0.65877008, 0.28230526, 0.77727285]])

In [ ]:
np.random.rand(4)

array([0.48727386, 0.22561751, 0.75776394, 0.05169971])

In [ ]:
np.random.rand(4,4)

array([[6.90847611e-01, 5.82335313e-01, 9.78916368e-01, 1.77857829e-01],
       [5.03178014e-01, 1.21631484e-01, 5.44769078e-02, 4.87678550e-01],
       [8.37236480e-01, 7.30644291e-01, 8.64888689e-04, 9.99402453e-02],
       [8.45775284e-01, 3.48475050e-01, 1.19118214e-02, 9.70316578e-01]])

In [ ]:
np.random.randint(1,15)

4

In [ ]:
np.random.randint(1,15,(10,10))

array([[ 8, 11,  2, 14, 12,  5,  8, 13,  6,  1],
       [ 7,  4, 10,  7, 14,  8,  4, 14,  3, 10],
       [12,  3,  5, 10,  6,  9,  6,  5, 13, 13],
       [ 6,  5,  5, 14, 14,  4, 14,  4, 12,  6],
       [ 1,  4,  1, 13,  4,  5, 13, 14,  4,  9],
       [ 2,  9,  6,  2,  3, 11,  3, 12, 12, 11],
       [ 4,  2,  7, 10,  5,  7,  2,  4,  7,  1],
       [14,  7,  5, 10,  3,  9, 12,  1,  5,  6],
       [12, 11,  6, 14, 11, 11, 13,  2,  5,  7],
       [ 4, 14,  4,  3, 14, 14,  3, 14,  1,  2]])