<a href="https://colab.research.google.com/github/Edgar0617/Platzi/blob/master/Dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Escalar

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

Vector

In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

Matriz

In [ ]:
matriz = np.array([[1,2,3],[4,5,8],[7,1,0],[2,0,1]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 8]
 [7 1 0]
 [2 0 1]]


2

Tensor

In [4]:
tensor = np.array([[[1,2,3],[4,5,8],[7,1,0],[2,0,1]],[[1,2,3],[4,5,8],[7,1,0],[2,0,1]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 8]
  [7 1 0]
  [2 0 1]]

 [[1 2 3]
  [4 5 8]
  [7 1 0]
  [2 0 1]]]


3

## Agregar o eliminar dimensiones

In [5]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [12]:
hola = np.expand_dims(np.array([1,2,3]),axis=1)
print(hola)
hola.ndim

[[1]
 [2]
 [3]]


2

In [14]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
