<a href="https://colab.research.google.com/github/Edgar0617/Platzi/blob/master/El_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
lista = [1,2,3,4,5,6,7,8,9]


In [30]:
arr = np.array(lista)

In [12]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[0] - arr[5]

-5

In [14]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matriz[2,2]

9

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[::4]

array([1, 5, 9])

In [22]:
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])