<a href="https://colab.research.google.com/github/Edgar0617/Platzi/blob/master/Funciones_principales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)
arr

array([14, 18,  3, 16, 16, 17,  1, 11,  8,  8])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[ 7, 10,  3,  5,  1],
       [14, 15,  4, 18, 18]])

## Traer el número mayor

In [ ]:
arr.max()

19

In [ ]:
matriz.max()

19

## Indice en el que está el mayor valor


In [ ]:
arr.argmax()

8

In [ ]:
matriz.argmax()

8

## Traer el número menor

In [ ]:
matriz.min()

4

In [ ]:
arr.min()

4

## Pico Mas alto y bajo

In [5]:
arr

array([14, 18,  3, 16, 16, 17,  1, 11,  8,  8])

In [ ]:
matriz

array([[ 7, 10,  3,  5,  1],
       [14, 15,  4, 18, 18]])

In [6]:
arr.ptp()

17

In [ ]:
matriz.ptp(0)

array([ 7,  5,  1, 13, 17])

## Percentil

In [7]:
np.percentile(arr,100)

18.0

## Ordenar los datos de menor a mayor

In [8]:
arr.sort()
arr

array([ 1,  3,  8,  8, 11, 14, 16, 16, 17, 18])

In [9]:
np.percentile(arr,50)

12.5

## Mediana

In [10]:
np.median(arr)

12.5

## Desviación estándar

In [16]:
np.std(arr)

5.706137047074842

## Varianza

In [12]:
np.var(arr)

32.559999999999995

## Media

In [18]:
np.mean(arr)

11.2