<a href="https://colab.research.google.com/github/Edgar0617/Platzi/blob/master/Matrices_y_vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
A = np.array([[2, 4], [-1, 2]])
A

array([[ 2,  4],
       [-1,  2]])

In [3]:
B = np.array([[1, 2], [0, 3]])
B

array([[1, 2],
       [0, 3]])

In [5]:
np.matmul(A, B)

array([[ 2, 16],
       [-1,  4]])

## Inversa

In [6]:
Ainversa = np.linalg.inv(A)
Ainversa

array([[ 0.25 , -0.5  ],
       [ 0.125,  0.25 ]])

In [7]:
np.matmul(A, Ainversa)


array([[1., 0.],
       [0., 1.]])

## Valores y Vectores

In [13]:
C = np.array([[1, 2], [1, 0]])
C

array([[1, 2],
       [1, 0]])

In [17]:
values, vectors = np.linalg.eig(C)
values, vectors

(array([ 2., -1.]), array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

In [18]:
np.matmul(C, vectors.T[1])

array([ 0.70710678, -0.70710678])

In [19]:
values[1]*vectors.T[1]

array([ 0.70710678, -0.70710678])