<a href="https://colab.research.google.com/github/Edgar0617/Platzi/blob/master/Shape%20y%20Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
hola = np.random.randint(1,10,(3,2))

## Shape me dice cuantas filas y cuantas columnas tengo

In [ ]:
hola.shape

(3, 2)

In [ ]:
hola

array([[5, 8],
       [3, 8],
       [8, 7]])

## Con reshape puedo cambiar la forma que tengo establecida en un Array

In [ ]:
hola.reshape(1,6)

array([[5, 8, 3, 8, 8, 7]])

In [ ]:
hola.reshape(2,3)

array([[5, 8, 3],
       [8, 8, 7]])

In [ ]:
np.reshape(hola,(1,6))

array([[5, 8, 3, 8, 8, 7]])

In [ ]:
hola

array([[5, 8],
       [3, 8],
       [8, 7]])

In [ ]:
np.reshape(hola,(1,6),"C")

array([[5, 8, 3, 8, 8, 7]])

In [4]:
print('Generando la matriz...')
arr_reto = np.random.randint(1,100,(4,6))
print(f'La matriz es esta\n{arr_reto}\ntiene {arr_reto.ndim} dimensiones')

print()

print('Intercambiando las dimensiones + ajuste dimensiones')
print('A')
arr_reto_dims = np.squeeze(arr_reto.reshape(1,24)) #Concatenando Squeeze con el reshape

print(f'La matriz es esta\n{arr_reto_dims}\ntiene {arr_reto_dims.ndim}')

print()
print('B')
arr_reto_dims = np.squeeze(arr_reto.reshape(8,3)) #Concatenando Squeeze con el reshape

print(f'La matriz es esta\n{arr_reto_dims}\ntiene {arr_reto_dims.ndim}')

print()
print('Generando un fallo intencional por incoherencia de dimensiones')
print('arr_reto.reshape(4,10) --> le paso 40 elementos y son 24')

Generando la matriz...
La matriz es esta
[[96 93 70  9 33  7]
 [67 94 50 61  5 85]
 [ 5 17 41 99 35  8]
 [47  8 78 10  8 62]]
tiene 2 dimensiones

Intercambiando las dimensiones + ajuste dimensiones
A
La matriz es esta
[96 93 70  9 33  7 67 94 50 61  5 85  5 17 41 99 35  8 47  8 78 10  8 62]
tiene 1

B
La matriz es esta
[[96 93 70]
 [ 9 33  7]
 [67 94 50]
 [61  5 85]
 [ 5 17 41]
 [99 35  8]
 [47  8 78]
 [10  8 62]]
tiene 2

Generando un fallo intencional por incoherencia de dimensiones
arr_reto.reshape(4,10) --> le paso 40 elementos y son 24
